In [6]:
import scipy.signal as signal
import numpy as np

```matlab
function [s,t,I,Q] = qpsk_mod(a,fc,OF)
%Modulate an incoming binary stream using conventional QPSK
%a - input binary data stream (0's and 1's) to modulate
%fc - carrier frequency in Hertz
%OF - oversampling factor (multiples of fc) - at least 4 is better
%s - QPSK modulated signal with carrier
%t - time base for the carrier modulated signal
%I - baseband I channel waveform (no carrier)
%Q - baseband Q channel waveform (no carrier)
L = 2*OF;%samples in each symbol (QPSK has 2 bits in each symbol)
ak = 2*a-1; %NRZ encoding 0-> -1, 1->+1
I = ak(1:2:end);Q = ak(2:2:end);%even and odd bit streams
I=repmat(I,1,L).'; Q=repmat(Q,1,L).';%even/odd streams at 1/2Tb baud
I = I(:).'; Q = Q(:).'; %serialize
fs = OF*fc; %sampling frequency
t=0:1/fs:(length(I)-1)/fs; %time base
iChannel = I.*cos(2*pi*fc*t);qChannel = -Q.*sin(2*pi*fc*t);
s = iChannel + qChannel; %QPSK modulated baseband signal
```

In [ ]:
def qpsk_mod(data: np.ndarray, freq_c: int, over_fact: int):
    """
    QPSK Modulator
    
    Parameters
    ----------
    data : ndarray 1xn
        Binary data - gray-coded or otherwise
    freq_c: int
        Carrier Frequency in Hz
    over_fact : int
        Oversampling Factor
    """
    bit2symbol = 2
    n_sps = bit2symbol * over_fact
    nrz_data = 2 * data - 1
    i_data, q_data = nrz_data[::2], nrz_data[1::2]
    

In [3]:
a = list(range(10))

In [5]:
a[1::2]

[1, 3, 5, 7, 9]

In [12]:
a = np.random.randint(0, 2, 10)

In [17]:
a

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 1])

In [29]:
np.repeat(a.reshape(-1,1), 2, axis=1).reshape(-1, 1)

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [26]:
a.reshape(-1, 1).repeat(

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 1])